server.port=9010



server.servlet.context-path=/inventory

#DB configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=Manursh@987
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#usually true for clients
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
#use ip instead of hostname for registration(useful for containers)
eureka.instance.prefer-ip-address=true
#default is 30
eureka.instance.lease-renewal-interval-in-seconds=10
#default is 90
eureka.instance.lease-expiration-duration-in-seconds=30
